---
title: "Lab and Workshop 1"
output: html_notebook
---

Taking help from RStudio for unknown formula:

```{r}
?dnorm
```

Creating variables:

```{r}
a<-1
b = 2
```

Creating vectors:

```{r}
b = c(1,2,3)
c = 1:3
d = seq(1,5,0.5)
e = rep(3,7)
```

Arithmetic operations:

```{r}
1*2*3
1/2/3
2**3
2^1.5
log(12)
exp(1)
pi
4*atan(1)
```

Concatenate vectors:

```{r}
ab = c(a,b)
```

Vector mathematics:

```{r}
2*b
b^2
sin(b)
```

Vector products:

```{r}
b*c
sum(b*c)
```

Central tendency:

```{r}
mean(b)
median(b)
min(b)
max(b)
```

Matrix:

```{r}
B = matrix(ncol=3, nrow=3)
B = matrix(0, 3, 3)
B = matrix(1:9, 3, 3)
B = matrix(1:9, 3, 3, byrow=TRUE)
```

Accessing matrix:

```{r}
B[2,2]
diag(B)
B[1,]
B[,2]
det(B)
solve(B)
```

Element-wise addition:

```{r}
C = diag(c(1,1,1))
solve(B+C)
```

Range extract:

```{r}
d[c(3,4,5,6)]
d[3:6]
d[-1]
d[-(1:2)]
```

Matrix multiplication:

```{r}
C = matrix(9:1,3,3)
B*C
B%*%C
```

More matrix functions:

```{r}
mean(B)
dim(B)
ncol(B)
nrow(B)
prod(B)
length(B)
```

Sorting:

```{r}
a = c(1,-5,3)
sort(a)
sort(C)
apply(C,2,sort)
apply(C, 1, sort)
t(apply(C, 1, sort))
```
