---
title: "Lab 10"
output: html_notebook
---

```{r}

library(readxl)
```

```{r}

Mozart = read_excel('/Users/rafsanalmamun/Desktop/MAST90105_Labs/Lab 10/Mozart.xls')

a = Mozart[, 2]
b = Mozart[, 1]
```

```{r}
Mozart = as.matrix(Mozart)
a = Mozart[, 2]
b = Mozart[, 1]
```

Task 1a

```{r}
total = a+b
plot(a, total)
```

Task 1b

```{r}

RegrM = lm(total ~ a)
RegrM0 = lm(total ~ a - 1)

plot(a, total)
abline(RegrM, lty='dotted', col='red')
abline(RegrM0, lty='dashed', col='green')

```

Task 1c

```{r}
phi = (sqrt(5) + 1)/2

plot(a, total)
abline(RegrM, lty='dotted', col='red')
abline(RegrM0, lty='dashed', col='green')

abline(a=0, b=phi, lty='dotdash', col='blue')
```

Task 1d

```{r}
mean(total/a)
phi
```

Task 1e

```{r}
plot(b, a)
```

```{r}
RegrME = lm(a~b)
summary(RegrME)
```

```{r}
RegrME0 = lm(a~0+b)
summary(RegrME0)
```

```{r}

plot(b, a)
abline(RegrME, lty='dotted', col='red')
abline(RegrME0, lty='dashed', col='green')
abline(a=0, b=phi, lty='dotdash', col='blue')
```

```{r}
mean(a/b)
```

Task 1f

```{r}
diff = a + b - phi * a

plot(a, RegrM$residuals, ylim=c(-15,20))
points(a, RegrM0$residuals, col='green', pch=0)
points(a, diff, col='red', pch=2)

```

```{r}
diff2 = a - phi * b

plot(b, RegrME$residuals, ylim=c(-30,30))
points(b, RegrME0$residuals, col='green', pch=0)
points(b, diff2, col='red', pch=2)
```
