---
title: "Lab 7"
output: html_notebook
---

Set the working directory

```{r}
setwd('/Users/rafsanalmamun/Desktop/MAST90105_Labs/Lab 7')
```

Load the data

```{r}
tasmania = read.csv('EditedRainfall.csv')
```

View the data and creating variables

```{r}

View(tasmania)
dim(tasmania) # check data dimension
names(tasmania[, 1:5]) # names of the first 5 columns
year = tasmania[, 1] # create a vector for year
s1 = tasmania[, 2] # create a vector for station 1 (Burnie)
s2 = tasmania[, 3] # create a vector for station 2 (Cape Grim)
```

Exploring the distribution of extreme rainfall in Burnie

```{r}

summary(s1) # 5-number summary plus sample mean
```

```{r}
sd(s1) # sample standard deviaion

IQR(s1) # IQR
```

```{r}
# sample percentiles using Type 6 and 7
# approximations
quantile(s1, type = 6)
quantile(s1, type = 7)
```

Exploring the distribution of extreme rainfall in Cape Grim

```{r}
summary(s2)

# remove the null values to calculate sd and IQR
sd(s2, na.rm = TRUE)
IQR(s2, na.rm = TRUE)
```

Exploring data by graphical summaries

```{r}

hist(s1, freq = FALSE, xlab = "Extreme rainfall (Burnie, Tas)") # freq = FALSE gives density
smooth.density = density(s1) # fits a smooth curve
points(smooth.density, type = "l", lty = 2, col = 2) # adds a smooth curve
```
