---
title: "Lab 9"
output: html_notebook
---

Task 1

```{r}
tasmania = read.csv("EditedRainfall.csv")
```

```{r}
s1 = tasmania[, 2] 
s2 = tasmania[, 3]
```

Task 2

```{r}
mu.hat = mean(s1)
mu.hat

n = length(s1)

sigma.hat = sqrt((n - 1) * var(s1)/n)
sigma.hat
```

```{r}
gumbel.fit1 = function(x, start = c(50, 10)) {
  n = length(x)

  likf = function(pr) {
    mu = pr[1]
    si = pr[2]
  
    if (si <= 0){
      return(1e+100)
    }
  
    sx = (x - mu)/si
    # minimize negative log-likelihood
    nloglik = n * log(si) + sum(sx) + sum(exp(-sx))
    nloglik
  }
  
  mle = nlm(likf, p = start)
  mle
}
```

```{r}
out1 = gumbel.fit1(s1, start = c(50, 10))
out1
```

```{r}
gumbel.fit2 = function(x, start = c(50, 10)) {
  n = length(x)

  likf = function(pr) {
    mu = pr[1]
    si = pr[2]
    sx = (x - mu)/si
    
    # minimize negative log-likelihood
    nloglik = n * log(si) + sum(sx) + sum(exp(-sx))
    nloglik
  }
  
  mle = optim(start, likf, method = "L-BFGS-B", lower = c(-50, 1e-04))
  mle
}
```

```{r}
out2 = gumbel.fit2(s1, start = c(50, 10))
out2
```

```{r}
library(MASS)
install.packages('evd',repos='https://cloud.r-project.org')
library(evd)
```

```{r}

# Write fitted normal and Gumbel pdfs
mu.hat2 = out1$estimate[1]
sigma.hat2 = out1$estimate[2]

pdf1 = function(x) {
  dnorm(x, mean = mu.hat, sd = sigma.hat)
}

pdf2 = function(x) {
  dgumbel(x, loc = mu.hat2, scale = sigma.hat2)
}

```

```{r}
# Plot data and fitted models
hist(s1, freq = FALSE, col = "gray", main = NULL, xlab = "x",
xlim = c(0, 100))
curve(pdf1, from = 0, to = 100, col = 2, lty = 2, lwd = 2,
add = TRUE)
curve(pdf2, from = 0, to = 100, col = 1, lty = 1, lwd = 2,
add = TRUE)
```

```{r}
out1$minimum #Gumbel negative log-likelihood
```

```{r}
n = length(s1)
nloglik = 0.5 * n * log(2 * pi) + n * log(sigma.hat) +
0.5 * sum((s1 - mu.hat)^2)/sigma.hat^2
nloglik # Normal negative log-likelihood
```

Task 3

```{r}
sigma.tilde = sqrt(6) * sigma.hat/pi
mu.tilde = mu.hat + digamma(1) * sigma.tilde

sigma.tilde
mu.tilde
```

Task 4

```{r}
# function to simulate from the Gumbel distribution
# with the same sample size as s1 and mle estimates
# for the parameters
rgum = function(x) {
  rgumbel(length(s1), loc = mu.hat2, scale = sigma.hat2)
}

# function to find the maximum likelihood
# estimators
fit.mle.gum = function(x) {
  out = gumbel.fit1(x, start = c(50, 10))
  out$estimate
}

# function to find the method of moments estimators
fit.mom.gum = function(x) {
  mu.hat = mean(x)
  sigma.hat = sqrt(var(x) * (length(x) - 1)/length(x))
  sigma.tilde = sqrt(6) * sigma.hat/pi
  mu.tilde = mu.hat + digamma(1) * sigma.tilde
  c(mu.tilde, sigma.tilde)
}

# simulate 1000 samples and obtain maximum
# likelihood estimates and method of moments
# estimates for each sample.
mle.est = matrix(nrow = 1000, ncol = 2)
mom.est = matrix(nrow = 1000, ncol = 2)
for (i in 1:1000) {
  x = rgum()
  mle.est[i, ] = fit.mle.gum(x)
  mom.est[i, ] = fit.mom.gum(x)
}

# means of estimators
mean.mle.est = apply(mle.est, 2, mean)
mean.mom.est = apply(mom.est, 2, mean)
mean.mle.est
mean.mom.est

# SDs of estimators
sd.mle.est = apply(mle.est, 2, sd)
sd.mom.est = apply(mom.est, 2, sd)
sd.mle.est
sd.mom.est
```
