---
title: "Lab 2: Calculating Probabilities and Plotting Distributions"
output: html_notebook
---

Task 1b:

Total lines of codes: 10000

Improvable: 30

Sample size: 10

```{r}
x = 0:10
prob = dhyper(x, 30, 9970, 10)
print(prob)
plot(x, prob, ylab="pmf", main="Hypergeometric Probabilities", lwd=2)
```

Task 1c:

```{r}
y1 = dhyper(x, 30, 970, 10)
y2 = dhyper(x, 30, 70, 10)
y3 = dhyper(x, 30, 20, 10)

plot(x, y1, ylab="pmf", main="Hypergeometric Probabilities", lwd=2, col="green")
lines(x, y2, ylab="pmf", lwd=2, col="red", type="p")
lines(x, y3, ylab="pmf", lwd=2, col="blue", type="p")
```

Task 2a, b:

Ai = i improvable lines

Pr(Ai) = 0.9/101; when meets standard

Pr(Ai) = 0.1/900; when not meets standard

B = 5 lines of code in the sample of 20 that could be improved

```{r}

i1 = 0:100
i2 = 101:1000

prb = (0.9/101)*sum(dhyper(5, i1, 1000-i1, 20)) + (0.1/900)*sum(dhyper(5, i2, 1000-i2, 20))

pr = rep(0, 1001)
pr[1:101] = (0.9/101)*dhyper(5, i1, 1000-i1, 20)/prb
pr[102:1001] = (0.1/900)*dhyper(5, i2, 1000-i2, 20)/prb
plot(0:1000, pr, xlab="x", ylab="pmf", lwd="2")
```

Task 2c:

```{r}

sum(pr[1:101])
```
