---
title: "Lab 4"
output: html_notebook
---

Task 1a

```{r}
# fix p and declare n as vector

n = c(1,10,50,100,250,500)
p = 0.1

m34binomial(n, p)
```

```{r}
p = 0.3

m34binomial(n, p)
```

```{r}
p = 0.5
m34binomial(n, p)
```

```{r}
p = 0.7
m34binomial(n, p)
```

```{r}
p = 0.9
m34binomial(n, p)
```

Task 1c

```{r}
# fix p and declare r as vector
r = c(1,10,50,100,250,500)
p = 0.1

m34negbinomial(r, p)
```

```{r}
p = 0.3
m34negbinomial(r, p)
```

```{r}
p = 0.5
m34negbinomial(r, p)
```

```{r}
p = 0.7
m34negbinomial(r, p)
```

```{r}
p = 0.9
m34negbinomial(r, p)
```

Task 2a

```{r}
# fix p, n and vary t as vector
n = 500
p = 0.1

distBinomHyper(n, p, t=n+100)
```

```{r}
p=0.3
distBinomHyper(n, p, n+100)
```

```{r}
p=0.1
distBinomHyper(n, p, n+1500)
```

```{r}
distBinomHyper(n, p, 16000000)
```

Task 3a

```{r}
distBinomPoisson = function(n,p){
  x=0:n
  lam = n*p
  pr1=dbinom(x,n,p)
  pr2=dpois(x,lam)
  D = 0.5*sum(abs(pr1-pr2)) + 0.5*ppois(n, lam, lower.tail = FALSE)
  
  #define the x values around the mean plus minus 5 st. deviations of the 
  #binomial distribution
  i.u=x < n*p + 5*sqrt(n*p*(1-p))
  i.l=x > n*p - 5*sqrt(n*p*(1-p))
  i.plot=i.u & i.l
  
  #round the distance down to first 3 digits after decimal point
  D1=floor(1000*D)/1000
  
  #plot the two pmf-s for x values around the mean plus minus 5 st. dev
  plot(x[i.plot],pr2[i.plot],type="p",col="orange",xlab="x", ylab="pmf", main=paste("D = ", D1), cex.main=1,lwd=2,cex=.5,ylim=c(0,max(c(pr1,pr2))))
  lines(x[i.plot],pr1[i.plot],type="p",col="blue",lwd=2,cex=.5)
  D
}
```
