---
title: "Lab 11"
output: html_notebook
---

Task 1

```{r}

x = t.test(rnorm(10))
x
names(x)
x$conf.int
```

```{r}
f=function(t){x=t.test(rnorm(t));as.vector(x$conf.int)};
f(10);
f(20);
t <- as.matrix(rep(10,100));
C <- t(apply(t,1,f)); #this is a trick so we don't have to program
matplot(C,type="l"); #a matrix plot
abline(0,0) #includes a line at 0
```

```{r}

num = (C[, 1] < 0) & (C[, 2] > 0)
sum(num)/nrow(C)
```

**Task 2a**

Prior, f(p) \~ U(0,1) \~ 1, 0\<p\<1

Posterior = L(p) \* f(p)

= p^675^ (1-p)^1149^ \* 1

Posterior = Beta(a=676, b=1150)

**Task 2b**

Prior, f(p) \~ Beta(a=676, b=1150) = B \* p^675^ (1-p)^1149^

L(p) = p^615^ (1-p)^1093^

Posterior = p^675^ (1-p)^1149^ \* p^615^ (1-p)^1093^

= p^1290^ (1-p)^2242^

= Beta(a=1291, b=2243)

**Task 2c**

f(p) \~ U(0,1) \~ 1, 0\<p\<1

Posterior = p^615^ (1-p)^1093^ \* 1

= Beta(a=616, b=1094)

```{r}

curve(dbeta(x, 1291, 2243), from=0.3, to=0.4, ylab='posterior pdf')
curve(dbeta(x, 616, 1094), from=0.3, to=0.4, add=TRUE, col='red', ylab='posterior pdf')
```

**Task 2d**

```{r}
qbeta(c(0.025, 0.975), 1291, 2243)
```

```{r}
qbeta(c(0.025, 0.975), 616, 1094)
```

**Task 2e**

Posterior mean based on first data = 676/(676+1150)

Pr(p\<0.5) = 0.99

```{r}
f2 = function(x){
  return (pbeta(0.5, 676*x, 1150*x) - 0.99)
}

uniroot(f2, c(0, 1000))
```

```{r}
676*0.043
1150*0.043
```

Prior = Beta(a=29.068, beta=49.45)
